spark.hadoop.fs.defaultFS                   hdfs://spark-master:8020
spark.yarn.resourcemanager.address          spark-master:8032
spark.driver.maxResultSize                  4g
spark.sql.shuffle.partitions                200
spark.files.maxPartitionBytes                134217728
spark.sql.files.maxPartitionBytes            134217728